trigger:
- main

pool:
 vmimage: ubuntu-latest

stages:
  - stage: ci
    jobs:
    - job: build
      steps:
      - script: echo "This is is build"
    - job: test
      steps:
      - script: echo "This is TEST"

  - stage: dockerpush
    jobs:
    - job: docker_push
      steps:
      - script: echo "Push docker image"    